# Generated by Django 3.2.7 on 2022-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.TextField(default='Test', max_length=500, verbose_name='Название тега'),
            preserve_default=False,
        ),
    ]
