# Generated by Django 3.2.7 on 2022-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220407_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fk_tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='news.Tag', verbose_name='Тэг'),
        ),
    ]
