# Generated by Django 3.2.7 on 2022-04-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_fk_tag_post_tag_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_state',
            field=models.ManyToManyField(blank=True, to='news.Tag', verbose_name='Тэг'),
        ),
    ]
