# Generated by Django 3.2.7 on 2022-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_post_tag_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_state',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_duraction',
            field=models.ManyToManyField(blank=True, related_name='posts', to='news.Tag', verbose_name='Тэг'),
        ),
    ]
