# Generated by Django 3.2.7 on 2022-04-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_post_tag_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'verbose_name': 'Статья', 'verbose_name_plural': 'Статья'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='',
        ),
    ]
