# Generated by Django 3.2.7 on 2022-04-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20220407_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_see_author', 'Может видеть только автор коментария'),), 'verbose_name': 'Комментариии', 'verbose_name_plural': 'Комментариии'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
