# Generated by Django 3.2.7 on 2022-04-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('can_see_guest', 'Можно видеть гость'),), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэг'},
        ),
    ]
